package ota.jw.AutoMappingWebAPI;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-05T16:01:31.713+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://www.opentravel.org/OTA/2003/05", name = "AutoMappingServicesSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface AutoMappingServicesSoap {

    /**
     * 获取携程子酒店信息
     */
    @WebMethod(operationName = "GetCtripSubHotelInfo", action = "http://htng.org/2014B/HTNG_ARIAndReservationPushService#GetCtripSubHotelInfo")
    @RequestWrapper(localName = "GetCtripSubHotelInfo", targetNamespace = "http://www.opentravel.org/OTA/2003/05", className = "ota.jw.AutoMappingWebAPI.GetCtripSubHotelInfo")
    @ResponseWrapper(localName = "GetCtripSubHotelInfoResponse", targetNamespace = "http://www.opentravel.org/OTA/2003/05", className = "ota.jw.AutoMappingWebAPI.GetCtripSubHotelInfoResponse")
    @WebResult(name = "CtripSubHotelInfoRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
    public ota.jw.AutoMappingWebAPI.CtripSubHotelInfoRS getCtripSubHotelInfo(
        @WebParam(name = "masterHotelId", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        java.lang.String masterHotelId
    );

    /**
     * 代理商、集团批量获取携程酒店
     */
    @WebMethod(operationName = "GetHotelInfo", action = "http://htng.org/2014B/HTNG_ARIAndReservationPushService#GetHotelInfo")
    @RequestWrapper(localName = "GetHotelInfo", targetNamespace = "http://www.opentravel.org/OTA/2003/05", className = "ota.jw.AutoMappingWebAPI.GetHotelInfo")
    @ResponseWrapper(localName = "GetHotelInfoResponse", targetNamespace = "http://www.opentravel.org/OTA/2003/05", className = "ota.jw.AutoMappingWebAPI.GetHotelInfoResponse")
    @WebResult(name = "GetHotelInfoRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
    public ota.jw.AutoMappingWebAPI.GetHotelInfoRS getHotelInfo(
        @WebParam(name = "GetHotelInfoRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        ota.jw.AutoMappingWebAPI.GetHotelInfoRQ getHotelInfoRQ
    );

    /**
     * 设置匹配
     */
    @WebMethod(operationName = "SetMappingInfo", action = "http://htng.org/2014B/HTNG_ARIAndReservationPushService#SetMappingInfo")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "SetMappingRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "SetMappingInfoResult")
    public SetMappingRS setMappingInfo(
        @WebParam(partName = "SetMappingRQ", name = "SetMappingRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        SetMappingRQ setMappingRQ
    );

    /**
     * 产品智能匹配
     */
    @WebMethod(operationName = "IntelligentMapping", action = "http://htng.org/2014B/HTNG_ARIAndReservationPushService#IntelligentMapping")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "IntelligentMappingRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "IntelligentMappingResult")
    public RoomMatchRS intelligentMapping(
        @WebParam(partName = "RoomMatchRQ", name = "IntelligentMappingRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        RoomMatchRQ roomMatchRQ
    );

    /**
     * 获取产品信息
     */
    @WebMethod(operationName = "GetRoomProductInfo", action = "http://htng.org/2014B/HTNG_ARIAndReservationPushService#GetRoomProductInfoRS")
    @RequestWrapper(localName = "GetRoomProductInfo", targetNamespace = "http://www.opentravel.org/OTA/2003/05", className = "ota.jw.AutoMappingWebAPI.GetRoomProductInfo")
    @ResponseWrapper(localName = "GetRoomProductInfoResponse", targetNamespace = "http://www.opentravel.org/OTA/2003/05", className = "ota.jw.AutoMappingWebAPI.GetRoomProductInfoResponse")
    @WebResult(name = "RoomProductInfoRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
    public ota.jw.AutoMappingWebAPI.ProductMappingInfoRS getRoomProductInfo(
        @WebParam(name = "subHotelId", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        java.lang.String subHotelId,
        @WebParam(name = "type", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        java.lang.String type
    );

    /**
     * 酒店产品结果查询
     */
    @WebMethod(operationName = "MappingStatusSearch", action = "http://htng.org/2014B/HTNG_ARIAndReservationPushService#MappingStatusSearch")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "MappingStatusSearchRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "MappingStatusSearchResult")
    public MappingStatusSearchRS mappingStatusSearch(
        @WebParam(partName = "MappingStatusSearchRQ", name = "MappingStatusSearchRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        MappingStatusSearchRQ mappingStatusSearchRQ
    );

    /**
     * 通过EBK账号获取携程子酒店信息
     */
    @WebMethod(operationName = "GetCtripSubHotelInfoByEBK", action = "http://htng.org/2014B/HTNG_ARIAndReservationPushService#GetCtripSubHotelInfoByEBK")
    @RequestWrapper(localName = "GetCtripSubHotelInfoByEBK", targetNamespace = "http://www.opentravel.org/OTA/2003/05", className = "ota.jw.AutoMappingWebAPI.GetCtripSubHotelInfoByEBK")
    @ResponseWrapper(localName = "GetCtripSubHotelInfoByEBKResponse", targetNamespace = "http://www.opentravel.org/OTA/2003/05", className = "ota.jw.AutoMappingWebAPI.GetCtripSubHotelInfoByEBKResponse")
    @WebResult(name = "CtripSubHotelInfoByEBKRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
    public ota.jw.AutoMappingWebAPI.CtripSubHotelInfoByEBKRS getCtripSubHotelInfoByEBK(
        @WebParam(name = "CtripSubHotelInfoByEBKRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        ota.jw.AutoMappingWebAPI.CtripSubHotelInfoByEBKRQ ctripSubHotelInfoByEBKRQ
    );
}
