
package ota.jw.AutoMappingWebAPI;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-05T16:01:31.726+08:00
 * Generated source version: 3.2.4
 *
 */

public class AutoMappingServicesSoap_AutoMappingServicesSoap_Server{

    protected AutoMappingServicesSoap_AutoMappingServicesSoap_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new AutoMappingServicesSoapImpl();
        String address = "http://124.127.242.67:38196/AutoMappingWebAPI/AutoMappingServices.asmx";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new AutoMappingServicesSoap_AutoMappingServicesSoap_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
