
package ota.jw.ARIAdapterGateWay;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-26T15:51:50.020+08:00
 * Generated source version: 3.2.4
 *
 */

public class ARIAdapterGateWaySoap_ARIAdapterGateWaySoap_Server{

    protected ARIAdapterGateWaySoap_ARIAdapterGateWaySoap_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ARIAdapterGateWaySoapImpl();
        String address = "http://124.127.242.67:38196/HW.ARIAdapterGateWay/ARIAdapterGateWay.asmx";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new ARIAdapterGateWaySoap_ARIAdapterGateWaySoap_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
