package ota.jw.ARIAdapterGateWay;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-26T15:51:49.996+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ARIAdapterGateWaySoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ARIAdapterGateWaySoap {

    /**
     * 获取厂商产品价格
     */
    @WebMethod(operationName = "QueryHotelRoomRate", action = "http://www.jointwisdom.cn#QueryHotelRoomRate")
    @WebResult(name = "QueryHotelRoomRateRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "QueryHotelRoomRateResult")
    public QueryHotelRoomRateRS queryHotelRoomRate(
        @WebParam(partName = "QueryHotelRoomRateRQ", name = "QueryHotelRoomRateRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        QueryHotelRoomRateRQ queryHotelRoomRateRQ
    );

    /**
     * 获取厂商实时房量
     */
    @WebMethod(operationName = "QueryHotelRoomCount", action = "http://www.jointwisdom.cn#QueryHotelRoomCount")
    @WebResult(name = "QueryHotelRoomCountRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "QueryHotelRoomCountResult")
    public QueryHotelRoomCountRS queryHotelRoomCount(
        @WebParam(partName = "QueryHotelRoomCountRQ", name = "QueryHotelRoomCountRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        QueryHotelRoomCountRQ queryHotelRoomCountRQ
    );

    /**
     * 获取厂商产品房态
     */
    @WebMethod(operationName = "QueryHotelAvailStatus", action = "http://www.jointwisdom.cn#QueryHotelAvailStatus")
    @WebResult(name = "QueryHotelAvailStatusRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "QueryHotelAvailStatusResult")
    public QueryHotelAvailStatusRS queryHotelAvailStatus(
        @WebParam(partName = "QueryHotelAvailStatusRQ", name = "QueryHotelAvailStatusRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        QueryHotelAvailStatusRQ queryHotelAvailStatusRQ
    );
}
