
package ota.jw.ws;

import javax.xml.ws.Endpoint;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import ota.jw.ws.impl.QueryHotelSoapImpl;

/**
 * This class was generated by Apache CXF 3.2.4 2018-07-26T15:51:50.020+08:00
 * Generated source version: 3.2.4
 *
 */

public class QueryServer {
	protected static Logger logger = LoggerFactory.getLogger(QueryServer.class);
	private static Endpoint queryEndpoint = null;

	public static void startOtaServer() {
		if (queryEndpoint == null) {
			//5.13. 获取厂商实时房量 
			QueryHotelSoapImpl implementor = new QueryHotelSoapImpl();
			String address = "http://localhost:8888/query";
			queryEndpoint = Endpoint.publish(address, implementor);
			logger.info("Starting QueryServer");
		} else {
			logger.debug("queryEndpoint 已经发布成功！！！！");
		}
	}

	public static void main(String args[]) throws java.lang.Exception {
		startOtaServer();
	}
}
