package ota.jw.AvailRes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-08-02T16:14:55.260+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://www.opentravel.org/OTA/2003/05", name = "AvailResSoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AvailResSoap {

    /**
     * 可订检查
     */
    @WebMethod(operationName = "CheckAvailability", action = "http://htng.org/2014B/HTNG_SeamlessShopAndBookService#CheckAvailability")
    @WebResult(name = "OTA_HotelAvailRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "CheckAvailabilityResult")
    public OTAHotelAvailRS checkAvailability(
        @WebParam(partName = "OTA_HotelAvailRQ", name = "OTA_HotelAvailRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        OTAHotelAvailRQ otaHotelAvailRQ
    );
}
