
package ota.jw.AvailRes;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-08-02T16:14:55.114+08:00
 * Generated source version: 3.2.4
 *
 */
public final class AvailResSoap_AvailResSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://www.opentravel.org/OTA/2003/05", "AvailRes");

    private AvailResSoap_AvailResSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AvailRes.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        AvailRes ss = new AvailRes(wsdlURL, SERVICE_NAME);
        AvailResSoap port = ss.getAvailResSoap();

        {
        System.out.println("Invoking checkAvailability...");
        ota.jw.AvailRes.OTAHotelAvailRQ _checkAvailability_otaHotelAvailRQ = null;
        ota.jw.AvailRes.OTAHotelAvailRS _checkAvailability__return = port.checkAvailability(_checkAvailability_otaHotelAvailRQ);
        System.out.println("checkAvailability.result=" + _checkAvailability__return);


        }

        System.exit(0);
    }

}
