
package ota.jw.ARIPmsGateway;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-04T16:34:03.427+08:00
 * Generated source version: 3.2.4
 *
 */

public class ARIGateWayServiceSoap_ARIGateWayServiceSoap12_Server{

    protected ARIGateWayServiceSoap_ARIGateWayServiceSoap12_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ARIGateWayServiceSoap12Impl();
        String address = "http://124.127.242.67:38196/PmsGateway/ARIGateWayService.asmx";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new ARIGateWayServiceSoap_ARIGateWayServiceSoap12_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
