
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ota.jw.ARIPmsGateway;

import java.util.logging.Logger;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-04T16:34:03.319+08:00
 * Generated source version: 3.2.4
 *
 */

@javax.jws.WebService(
                      serviceName = "ARIGateWayService",
                      portName = "ARIGateWayServiceHttpGet",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "http://124.127.242.67:38196/PmsGateway/ARIGateWayService.asmx?WSDL",
                      endpointInterface = "ota.jw.ARIPmsGateway.ARIGateWayServiceHttpGet")

public class ARIGateWayServiceHttpGetImpl implements ARIGateWayServiceHttpGet {

    private static final Logger LOG = Logger.getLogger(ARIGateWayServiceHttpGetImpl.class.getName());

}
