
package ota.jw.ARIPmsGateway;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-04T16:34:03.424+08:00
 * Generated source version: 3.2.4
 *
 */

public class ARIGateWayServiceHttpGet_ARIGateWayServiceHttpGet_Server{

    protected ARIGateWayServiceHttpGet_ARIGateWayServiceHttpGet_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ARIGateWayServiceHttpGetImpl();
        String address = "CHANGE_ME";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new ARIGateWayServiceHttpGet_ARIGateWayServiceHttpGet_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
