package ota.jw.ARIPmsGateway;

import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-04T16:34:03.381+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ARIGateWayServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
public interface ARIGateWayServiceHttpPost {
}
