package ota.jw.ARIPmsGateway;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-04T16:34:03.407+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ARIGateWayServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ARIGateWayServiceSoap {

    /**
     * ARI房态设置
     */
    @WebMethod(operationName = "OTA_HotelAvailNotifRQ", action = "http://htng.org/2014B/HTNG_ARIAndReservationPushService#OTA_HotelAvailNotifRQ")
    @WebResult(name = "OTA_HotelAvailNotifRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "OTA_HotelAvailNotifRQResult")
    public OTAHotelAvailNotifRS otaHotelAvailNotifRQ(
        @WebParam(partName = "OTA_HotelAvailNotifRQ1", name = "OTA_HotelAvailNotifRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        OTAHotelAvailNotifRQ otaHotelAvailNotifRQ1
    );

    /**
     * ARI推送房价
     */
    @WebMethod(operationName = "OTA_HotelRatePlanNotifRQ", action = "http://htng.org/2014B/HTNG_ARIAndReservationPushService#OTA_HotelRatePlanNotifRQ")
    @WebResult(name = "OTA_HotelRatePlanNotifRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "OTA_HotelRatePlanNotifRQResult")
    public OTAHotelRatePlanNotifRS otaHotelRatePlanNotifRQ(
        @WebParam(partName = "OTA_HotelRatePlanNotifRQ1", name = "OTA_HotelRatePlanNotifRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        OTAHotelRatePlanNotifRQ otaHotelRatePlanNotifRQ1
    );

    /**
     * 库存(实时房量)
     */
    @WebMethod(operationName = "OTA_HotelInvCountNotifRQ", action = "http://htng.org/2014B/HTNG_ARIAndReservationPushService#OTA_HotelInvCountNotifRQ")
    @WebResult(name = "OTA_HotelInvCountNotifRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "OTA_HotelInvCountNotifRQResult")
    public OTAHotelInvCountNotifRS otaHotelInvCountNotifRQ(
        @WebParam(partName = "OTA_HotelInvCountNotifRQ1", name = "OTA_HotelInvCountNotifRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        OTAHotelInvCountNotifRQ otaHotelInvCountNotifRQ1
    );
}
