
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ota.jw.ARIPmsGateway;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-04T16:34:03.326+08:00
 * Generated source version: 3.2.4
 *
 */

@javax.jws.WebService(
                      serviceName = "ARIGateWayService",
                      portName = "ARIGateWayServiceSoap12",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "http://124.127.242.67:38196/PmsGateway/ARIGateWayService.asmx?WSDL",
                      endpointInterface = "ota.jw.ARIPmsGateway.ARIGateWayServiceSoap")

public class ARIGateWayServiceSoap12Impl implements ARIGateWayServiceSoap {

    private static final Logger LOG = Logger.getLogger(ARIGateWayServiceSoap12Impl.class.getName());

    /* (non-Javadoc)
     * @see ota.jw.ARIPmsGateway.ARIGateWayServiceSoap#otaHotelAvailNotifRQ(ota.jw.ARIPmsGateway.OTAHotelAvailNotifRQ otaHotelAvailNotifRQ1)*
     */
    public ota.jw.ARIPmsGateway.OTAHotelAvailNotifRS otaHotelAvailNotifRQ(OTAHotelAvailNotifRQ otaHotelAvailNotifRQ1) {
        LOG.info("Executing operation otaHotelAvailNotifRQ");
        System.out.println(otaHotelAvailNotifRQ1);
        try {
            ota.jw.ARIPmsGateway.OTAHotelAvailNotifRS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ota.jw.ARIPmsGateway.ARIGateWayServiceSoap#otaHotelRatePlanNotifRQ(ota.jw.ARIPmsGateway.OTAHotelRatePlanNotifRQ otaHotelRatePlanNotifRQ1)*
     */
    public ota.jw.ARIPmsGateway.OTAHotelRatePlanNotifRS otaHotelRatePlanNotifRQ(OTAHotelRatePlanNotifRQ otaHotelRatePlanNotifRQ1) {
        LOG.info("Executing operation otaHotelRatePlanNotifRQ");
        System.out.println(otaHotelRatePlanNotifRQ1);
        try {
            ota.jw.ARIPmsGateway.OTAHotelRatePlanNotifRS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ota.jw.ARIPmsGateway.ARIGateWayServiceSoap#otaHotelInvCountNotifRQ(ota.jw.ARIPmsGateway.OTAHotelInvCountNotifRQ otaHotelInvCountNotifRQ1)*
     */
    public ota.jw.ARIPmsGateway.OTAHotelInvCountNotifRS otaHotelInvCountNotifRQ(OTAHotelInvCountNotifRQ otaHotelInvCountNotifRQ1) {
        LOG.info("Executing operation otaHotelInvCountNotifRQ");
        System.out.println(otaHotelInvCountNotifRQ1);
        try {
            ota.jw.ARIPmsGateway.OTAHotelInvCountNotifRS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
