
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ota.jw.GenericSeamlessGateway;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-06T11:11:56.713+08:00
 * Generated source version: 3.2.4
 *
 */

@javax.jws.WebService(
                      serviceName = "AvailRes",
                      portName = "AvailResSoap",
                      targetNamespace = "http://www.opentravel.org/OTA/2003/05",
                      wsdlLocation = "http://124.127.242.67:38196/GenericSeamlessGateway/AvailRes.asmx?wsdl",
                      endpointInterface = "ota.jw.GenericSeamlessGateway.AvailResSoap")

public class AvailResSoapImpl implements AvailResSoap {

    private static final Logger LOG = Logger.getLogger(AvailResSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see ota.jw.GenericSeamlessGateway.AvailResSoap#checkAvailability(ota.jw.GenericSeamlessGateway.OTAHotelAvailRQ otaHotelAvailRQ)*
     */
    public ota.jw.GenericSeamlessGateway.OTAHotelAvailRS checkAvailability(OTAHotelAvailRQ otaHotelAvailRQ) {
        LOG.info("Executing operation checkAvailability");
        System.out.println(otaHotelAvailRQ);
        try {
            ota.jw.GenericSeamlessGateway.OTAHotelAvailRS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
