
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ota.jw.GenericSeamlessGateway;

import java.util.logging.Logger;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-06T11:11:56.743+08:00
 * Generated source version: 3.2.4
 *
 */

@javax.jws.WebService(
                      serviceName = "AvailRes",
                      portName = "AvailResHttpPost",
                      targetNamespace = "http://www.opentravel.org/OTA/2003/05",
                      wsdlLocation = "http://124.127.242.67:38196/GenericSeamlessGateway/AvailRes.asmx?wsdl",
                      endpointInterface = "ota.jw.GenericSeamlessGateway.AvailResHttpPost")

public class AvailResHttpPostImpl implements AvailResHttpPost {

    private static final Logger LOG = Logger.getLogger(AvailResHttpPostImpl.class.getName());

}
