package ota.jw.GenericSeamlessGateway;

import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-06T11:11:56.775+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://www.opentravel.org/OTA/2003/05", name = "AvailResHttpPost")
@XmlSeeAlso({ObjectFactory.class})
public interface AvailResHttpPost {
}
