
package ota.jw.GenericSeamlessGateway;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-25T15:29:21.931+08:00
 * Generated source version: 3.2.4
 *
 */

public class BookingReservationHttpPost_BookingReservationHttpPost_Server{

    protected BookingReservationHttpPost_BookingReservationHttpPost_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new BookingReservationHttpPostImpl();
        String address = "CHANGE_ME";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new BookingReservationHttpPost_BookingReservationHttpPost_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
