
package ota.jw.GenericSeamlessGateway;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-25T15:29:21.935+08:00
 * Generated source version: 3.2.4
 *
 */

public class BookingReservationSoap_BookingReservationSoap12_Server{

    protected BookingReservationSoap_BookingReservationSoap12_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new BookingReservationSoap12Impl();
        String address = "http://124.127.242.67:38196/GenericSeamlessGateway/CreateBookingReservation.asmx";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new BookingReservationSoap_BookingReservationSoap12_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
