package ota.jw.GenericSeamlessGateway;

import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-25T15:29:21.924+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://www.opentravel.org/OTA/2003/05", name = "BookingReservationHttpGet")
@XmlSeeAlso({ObjectFactory.class})
public interface BookingReservationHttpGet {
}
