
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ota.jw.GenericSeamlessGateway;

import java.util.logging.Logger;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-25T15:29:21.903+08:00
 * Generated source version: 3.2.4
 *
 */

@javax.jws.WebService(
                      serviceName = "BookingReservation",
                      portName = "BookingReservationHttpGet",
                      targetNamespace = "http://www.opentravel.org/OTA/2003/05",
                      wsdlLocation = "http://124.127.242.67:38196/GenericSeamlessGateway/CreateBookingReservation.asmx?WSDL",
                      endpointInterface = "ota.jw.GenericSeamlessGateway.BookingReservationHttpGet")

public class BookingReservationHttpGetImpl implements BookingReservationHttpGet {

    private static final Logger LOG = Logger.getLogger(BookingReservationHttpGetImpl.class.getName());

}
