package ota.jw.GenericSeamlessGateway;

import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-25T15:29:59.865+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://Booking.hw/", name = "CancelBookingReservationHttpGet")
@XmlSeeAlso({ObjectFactory.class})
public interface CancelBookingReservationHttpGet {
}
