package ota.jw.GenericSeamlessGateway;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-25T15:29:59.852+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://Booking.hw/", name = "CancelBookingReservationSoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CancelBookingReservationSoap {

    /**
     * 取消订单
     */
    @WebMethod(operationName = "ProcessReservationRequest", action = "http://htng.org/2014B/HTNG_SeamlessShopAndBookService#ProcessReservationRequest")
    @WebResult(name = "OTA_HotelResRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "ProcessReservationRequestResult")
    public OTAHotelResRS processReservationRequest(
        @WebParam(partName = "OTA_HotelResRQ", name = "OTA_HotelResRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        OTAHotelResRQ otaHotelResRQ
    );
}
