
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ota.jw.GenericSeamlessGateway;

import java.util.logging.Logger;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-25T15:29:59.833+08:00
 * Generated source version: 3.2.4
 *
 */

@javax.jws.WebService(
                      serviceName = "CancelBookingReservation",
                      portName = "CancelBookingReservationHttpPost",
                      targetNamespace = "http://Booking.hw/",
                      wsdlLocation = "http://124.127.242.67:38196/GenericSeamlessGateway/CancelBookingReservation.asmx?WSDL",
                      endpointInterface = "ota.jw.GenericSeamlessGateway.CancelBookingReservationHttpPost")

public class CancelBookingReservationHttpPostImpl implements CancelBookingReservationHttpPost {

    private static final Logger LOG = Logger.getLogger(CancelBookingReservationHttpPostImpl.class.getName());

}
