package ota.jw.AutoMappingWS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-02T17:28:15.686+08:00
 * Generated source version: 3.2.4
 *	测试地址：http://124.127.242.67:38196/AutoMappingWS/GetPmsInfo.asmx?WSDL
 */
@WebServiceClient(name = "GetPmsInfo",
                  wsdlLocation = "http://switchapp.hubwisdom.cn/AutoMappingWS/GetPmsInfo.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/")
public class GetPmsInfo extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "GetPmsInfo");
    public final static QName GetPmsInfoHttpGet = new QName("http://tempuri.org/", "GetPmsInfoHttpGet");
    public final static QName GetPmsInfoHttpPost = new QName("http://tempuri.org/", "GetPmsInfoHttpPost");
    public final static QName GetPmsInfoSoap = new QName("http://tempuri.org/", "GetPmsInfoSoap");
    public final static QName GetPmsInfoSoap12 = new QName("http://tempuri.org/", "GetPmsInfoSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://switchapp.hubwisdom.cn/AutoMappingWS/GetPmsInfo.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetPmsInfo.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://switchapp.hubwisdom.cn/AutoMappingWS/GetPmsInfo.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public GetPmsInfo(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetPmsInfo(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetPmsInfo() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GetPmsInfo(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GetPmsInfo(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GetPmsInfo(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns GetPmsInfoHttpGet
     */
    @WebEndpoint(name = "GetPmsInfoHttpGet")
    public GetPmsInfoHttpGet getGetPmsInfoHttpGet() {
        return super.getPort(GetPmsInfoHttpGet, GetPmsInfoHttpGet.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetPmsInfoHttpGet
     */
    @WebEndpoint(name = "GetPmsInfoHttpGet")
    public GetPmsInfoHttpGet getGetPmsInfoHttpGet(WebServiceFeature... features) {
        return super.getPort(GetPmsInfoHttpGet, GetPmsInfoHttpGet.class, features);
    }


    /**
     *
     * @return
     *     returns GetPmsInfoHttpPost
     */
    @WebEndpoint(name = "GetPmsInfoHttpPost")
    public GetPmsInfoHttpPost getGetPmsInfoHttpPost() {
        return super.getPort(GetPmsInfoHttpPost, GetPmsInfoHttpPost.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetPmsInfoHttpPost
     */
    @WebEndpoint(name = "GetPmsInfoHttpPost")
    public GetPmsInfoHttpPost getGetPmsInfoHttpPost(WebServiceFeature... features) {
        return super.getPort(GetPmsInfoHttpPost, GetPmsInfoHttpPost.class, features);
    }


    /**
     *
     * @return
     *     returns GetPmsInfoSoap
     */
    @WebEndpoint(name = "GetPmsInfoSoap")
    public GetPmsInfoSoap getGetPmsInfoSoap() {
        return super.getPort(GetPmsInfoSoap, GetPmsInfoSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetPmsInfoSoap
     */
    @WebEndpoint(name = "GetPmsInfoSoap")
    public GetPmsInfoSoap getGetPmsInfoSoap(WebServiceFeature... features) {
        return super.getPort(GetPmsInfoSoap, GetPmsInfoSoap.class, features);
    }


    /**
     *
     * @return
     *     returns GetPmsInfoSoap
     */
    @WebEndpoint(name = "GetPmsInfoSoap12")
    public GetPmsInfoSoap getGetPmsInfoSoap12() {
        return super.getPort(GetPmsInfoSoap12, GetPmsInfoSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetPmsInfoSoap
     */
    @WebEndpoint(name = "GetPmsInfoSoap12")
    public GetPmsInfoSoap getGetPmsInfoSoap12(WebServiceFeature... features) {
        return super.getPort(GetPmsInfoSoap12, GetPmsInfoSoap.class, features);
    }

}
