package ota.jw.AutoMappingWS;

import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-02T17:28:15.631+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "GetPmsInfoHttpGet")
@XmlSeeAlso({ObjectFactory.class})
public interface GetPmsInfoHttpGet {
}
