package ota.jw.AutoMappingWS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-02T17:28:15.648+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "GetPmsInfoSoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetPmsInfoSoap {

    /**
     * 获取PMS酒店信息
     */
    @WebMethod(operationName = "GetAllPmsHotelInfo", action = "http://htng.org/2014B/HTNG_ARIAndReservationPushService#GetPMSHotelInfo")
    @WebResult(name = "PmsHotelInfoRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "GetAllPmsHotelInfoResult")
    public PMSHotelMapingRS getAllPmsHotelInfo(
        @WebParam(partName = "PmsHotelInfoRQ", name = "PmsHotelInfoRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        PmsHotelInfoRQ pmsHotelInfoRQ
    );

    /**
     * PMS通知OTA下线服务
     */
    @WebMethod(operationName = "PMSNotifyOnOffline", action = "http://htng.org/2014B/HTNG_ARIAndReservationPushService#PMSNotifyOnOffInfo")
    @WebResult(name = "PMSNotifyOnOffInfoRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "PMSNotifyOnOfflineResult")
    public NotifyOnOffInfoRS pmsNotifyOnOffline(
        @WebParam(partName = "PMSNotifyOnOffInfoRQ", name = "PMSNotifyOnOffInfoRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        PMSNotifyOTAModelRQ pmsNotifyOnOffInfoRQ
    );
}
