
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ota.jw.AutoMappingWS;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-02T17:28:15.609+08:00
 * Generated source version: 3.2.4
 *
 */

@javax.jws.WebService(
                      serviceName = "GetPmsInfo",
                      portName = "GetPmsInfoSoap12",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "http://124.127.242.67:38196/AutoMappingWS/GetPmsInfo.asmx?WSDL",
                      endpointInterface = "ota.jw.AutoMappingWS.GetPmsInfoSoap")

public class GetPmsInfoSoap12Impl implements GetPmsInfoSoap {

    private static final Logger LOG = Logger.getLogger(GetPmsInfoSoap12Impl.class.getName());

    /* (non-Javadoc)
     * @see ota.jw.AutoMappingWS.GetPmsInfoSoap#getAllPmsHotelInfo(ota.jw.AutoMappingWS.PmsHotelInfoRQ pmsHotelInfoRQ)*
     */
    public ota.jw.AutoMappingWS.PMSHotelMapingRS getAllPmsHotelInfo(PmsHotelInfoRQ pmsHotelInfoRQ) {
        LOG.info("Executing operation getAllPmsHotelInfo");
        System.out.println(pmsHotelInfoRQ);
        try {
            ota.jw.AutoMappingWS.PMSHotelMapingRS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ota.jw.AutoMappingWS.GetPmsInfoSoap#pmsNotifyOnOffline(ota.jw.AutoMappingWS.PMSNotifyOTAModelRQ pmsNotifyOnOffInfoRQ)*
     */
    public ota.jw.AutoMappingWS.NotifyOnOffInfoRS pmsNotifyOnOffline(PMSNotifyOTAModelRQ pmsNotifyOnOffInfoRQ) {
        LOG.info("Executing operation pmsNotifyOnOffline");
        System.out.println(pmsNotifyOnOffInfoRQ);
        try {
            ota.jw.AutoMappingWS.NotifyOnOffInfoRS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
