
package ota.jw.AutoMappingWS;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-02T17:28:15.550+08:00
 * Generated source version: 3.2.4
 *
 */
public final class GetPmsInfoSoap_GetPmsInfoSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "GetPmsInfo");

    private GetPmsInfoSoap_GetPmsInfoSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GetPmsInfo.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        GetPmsInfo ss = new GetPmsInfo(wsdlURL, SERVICE_NAME);
        GetPmsInfoSoap port = ss.getGetPmsInfoSoap12();

        {
        System.out.println("Invoking getAllPmsHotelInfo...");
        ota.jw.AutoMappingWS.PmsHotelInfoRQ _getAllPmsHotelInfo_pmsHotelInfoRQ = null;
        ota.jw.AutoMappingWS.PMSHotelMapingRS _getAllPmsHotelInfo__return = port.getAllPmsHotelInfo(_getAllPmsHotelInfo_pmsHotelInfoRQ);
        System.out.println("getAllPmsHotelInfo.result=" + _getAllPmsHotelInfo__return);


        }
        {
        System.out.println("Invoking pmsNotifyOnOffline...");
        ota.jw.AutoMappingWS.PMSNotifyOTAModelRQ _pmsNotifyOnOffline_pmsNotifyOnOffInfoRQ = null;
        ota.jw.AutoMappingWS.NotifyOnOffInfoRS _pmsNotifyOnOffline__return = port.pmsNotifyOnOffline(_pmsNotifyOnOffline_pmsNotifyOnOffInfoRQ);
        System.out.println("pmsNotifyOnOffline.result=" + _pmsNotifyOnOffline__return);


        }

        System.exit(0);
    }

}
