
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ota.jw.AutoMappingWS;

import java.util.logging.Logger;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-02T17:28:15.576+08:00
 * Generated source version: 3.2.4
 *
 */

@javax.jws.WebService(
                      serviceName = "GetPmsInfo",
                      portName = "GetPmsInfoHttpPost",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "http://124.127.242.67:38196/AutoMappingWS/GetPmsInfo.asmx?WSDL",
                      endpointInterface = "ota.jw.AutoMappingWS.GetPmsInfoHttpPost")

public class GetPmsInfoHttpPostImpl implements GetPmsInfoHttpPost {

    private static final Logger LOG = Logger.getLogger(GetPmsInfoHttpPostImpl.class.getName());

}
