
package ota.jw.PMSGateway;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-25T14:50:06.343+08:00
 * Generated source version: 3.2.4
 *
 */
public final class PMSGatewayServiceSoap_PMSGatewayServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "PMSGatewayService");

    private PMSGatewayServiceSoap_PMSGatewayServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PMSGatewayService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        PMSGatewayService ss = new PMSGatewayService(wsdlURL, SERVICE_NAME);
        PMSGatewayServiceSoap port = ss.getPMSGatewayServiceSoap();

        {
        System.out.println("Invoking otaHotelStayInfoNotifRQ...");
        ota.jw.PMSGateway.OTAHotelStayInfoNotifRQ _otaHotelStayInfoNotifRQ_otaHotelRatePlanNotifRQ1 = null;
        ota.jw.PMSGateway.OTAHotelStayInfoNotifRS _otaHotelStayInfoNotifRQ__return = port.otaHotelStayInfoNotifRQ(_otaHotelStayInfoNotifRQ_otaHotelRatePlanNotifRQ1);
        System.out.println("otaHotelStayInfoNotifRQ.result=" + _otaHotelStayInfoNotifRQ__return);


        }
        {
        System.out.println("Invoking pmsInHouseNotice...");
        ota.jw.PMSGateway.OrderCheckInNoticeRQ _pmsInHouseNotice_orderCheckInNoticeRQ = null;
        ota.jw.PMSGateway.OrderCheckInNoticeRS _pmsInHouseNotice__return = port.pmsInHouseNotice(_pmsInHouseNotice_orderCheckInNoticeRQ);
        System.out.println("pmsInHouseNotice.result=" + _pmsInHouseNotice__return);


        }
        {
        System.out.println("Invoking updateRetrievedPrdStatus...");
        ota.jw.PMSGateway.OTAPrdNotifReportRQ _updateRetrievedPrdStatus_otaNotifReportRQ = null;
        ota.jw.PMSGateway.MessageAcknowledgementType _updateRetrievedPrdStatus__return = port.updateRetrievedPrdStatus(_updateRetrievedPrdStatus_otaNotifReportRQ);
        System.out.println("updateRetrievedPrdStatus.result=" + _updateRetrievedPrdStatus__return);


        }
        {
        System.out.println("Invoking otaHotelRatePlanNotifRQ...");
        ota.jw.PMSGateway.OTAHotelRatePlanNotifRQ _otaHotelRatePlanNotifRQ_otaHotelRatePlanNotifRQ1 = null;
        ota.jw.PMSGateway.OTAHotelRatePlanNotifRS _otaHotelRatePlanNotifRQ__return = port.otaHotelRatePlanNotifRQ(_otaHotelRatePlanNotifRQ_otaHotelRatePlanNotifRQ1);
        System.out.println("otaHotelRatePlanNotifRQ.result=" + _otaHotelRatePlanNotifRQ__return);


        }
        {
        System.out.println("Invoking otaHotelInvCountNotifRQ...");
        ota.jw.PMSGateway.OTAHotelInvCountNotifRQ _otaHotelInvCountNotifRQ_otaHotelInvCountNotifRQ1 = null;
        ota.jw.PMSGateway.OTAHotelInvCountNotifRS _otaHotelInvCountNotifRQ__return = port.otaHotelInvCountNotifRQ(_otaHotelInvCountNotifRQ_otaHotelInvCountNotifRQ1);
        System.out.println("otaHotelInvCountNotifRQ.result=" + _otaHotelInvCountNotifRQ__return);


        }
        {
        System.out.println("Invoking otaHotelAvailNotifRQ...");
        ota.jw.PMSGateway.OTAHotelAvailNotifRQ _otaHotelAvailNotifRQ_otaHotelAvailNotifRQ1 = null;
        ota.jw.PMSGateway.OTAHotelAvailNotifRS _otaHotelAvailNotifRQ__return = port.otaHotelAvailNotifRQ(_otaHotelAvailNotifRQ_otaHotelAvailNotifRQ1);
        System.out.println("otaHotelAvailNotifRQ.result=" + _otaHotelAvailNotifRQ__return);


        }
        {
        System.out.println("Invoking pmsRetrivePrdInfo...");
        ota.jw.PMSGateway.OTAPrdReadRQ _pmsRetrivePrdInfo_otaReadRQ = null;
        ota.jw.PMSGateway.OrderPaymentInfoRS _pmsRetrivePrdInfo__return = port.pmsRetrivePrdInfo(_pmsRetrivePrdInfo_otaReadRQ);
        System.out.println("pmsRetrivePrdInfo.result=" + _pmsRetrivePrdInfo__return);


        }
        {
        System.out.println("Invoking pmsOrderStatusPush...");
        ota.jw.PMSGateway.OTAPushOrderStatusRQ _pmsOrderStatusPush_otaPushOrderStatusRQ = null;
        ota.jw.PMSGateway.OTAPushOrderStatusRS _pmsOrderStatusPush__return = port.pmsOrderStatusPush(_pmsOrderStatusPush_otaPushOrderStatusRQ);
        System.out.println("pmsOrderStatusPush.result=" + _pmsOrderStatusPush__return);


        }
        {
        System.out.println("Invoking retrieveReservations...");
        ota.jw.PMSGateway.OTAReadRQ _retrieveReservations_otaReadRQ = null;
        ota.jw.PMSGateway.OTAResRetrieveRS _retrieveReservations__return = port.retrieveReservations(_retrieveReservations_otaReadRQ);
        System.out.println("retrieveReservations.result=" + _retrieveReservations__return);


        }
        {
        System.out.println("Invoking pmsCheckedOutNotice...");
        ota.jw.PMSGateway.OrderApplyPaymentRQ _pmsCheckedOutNotice_orderApplyPaymentRQ = null;
        ota.jw.PMSGateway.OrderApplyPaymentRS _pmsCheckedOutNotice__return = port.pmsCheckedOutNotice(_pmsCheckedOutNotice_orderApplyPaymentRQ);
        System.out.println("pmsCheckedOutNotice.result=" + _pmsCheckedOutNotice__return);


        }
        {
        System.out.println("Invoking updatePulledReservations...");
        ota.jw.PMSGateway.OTANotifReportRQ _updatePulledReservations_otaNotifReportRQ = null;
        ota.jw.PMSGateway.MessageAcknowledgementType _updatePulledReservations__return = port.updatePulledReservations(_updatePulledReservations_otaNotifReportRQ);
        System.out.println("updatePulledReservations.result=" + _updatePulledReservations__return);


        }

        System.exit(0);
    }

}
