
package ota.jw.PMSGateway;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-25T14:50:06.488+08:00
 * Generated source version: 3.2.4
 *
 */

public class PMSGatewayServiceSoap_PMSGatewayServiceSoap12_Server{

    protected PMSGatewayServiceSoap_PMSGatewayServiceSoap12_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new PMSGatewayServiceSoap12Impl();
        String address = "http://124.127.242.67:38196/PMSGateway/PMSGatewayService.asmx";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new PMSGatewayServiceSoap_PMSGatewayServiceSoap12_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
