package ota.jw.PMSGateway;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-25T14:50:06.457+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "PMSGatewayServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PMSGatewayServiceSoap {

    /**
     * 订单审核(入住，离店，NoShow)
     */
    @WebMethod(operationName = "OTA_HotelStayInfoNotifRQ", action = "http://htng.org/2014B/HTNG_ARIAndReservationPushService#OTA_HotelStayInfoNotifRQ")
    @WebResult(name = "OTA_HotelStayInfoNotifRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "OTA_HotelStayInfoNotifRQResult")
    public OTAHotelStayInfoNotifRS otaHotelStayInfoNotifRQ(
        @WebParam(partName = "OTA_HotelRatePlanNotifRQ1", name = "OTA_HotelStayInfoNotifRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        OTAHotelStayInfoNotifRQ otaHotelRatePlanNotifRQ1
    );

    /**
     * 预授权---入住
     */
    @WebMethod(operationName = "PmsInHouseNotice", action = "http://htng.org/2014B/HTNG_ARIAndReservationPushService#OrderCheckInNoticeRQ")
    @WebResult(name = "OrderCheckInNoticeRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "PmsInHouseNoticeResult")
    public OrderCheckInNoticeRS pmsInHouseNotice(
        @WebParam(partName = "OrderCheckInNoticeRQ", name = "OrderCheckInNoticeRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        OrderCheckInNoticeRQ orderCheckInNoticeRQ
    );

    /**
     * 确认预授权
     */
    @WebMethod(operationName = "UpdateRetrievedPrdStatus", action = "http://htng.org/2014B/HTNG_ARIAndReservationPullService#OTA_PrdNotifReportRQ")
    @WebResult(name = "MessageAcknowledgementType", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "UpdateRetrievedPrdStatusResult")
    public MessageAcknowledgementType updateRetrievedPrdStatus(
        @WebParam(partName = "OTA_NotifReportRQ", name = "OTA_PrdNotifReportRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        OTAPrdNotifReportRQ otaNotifReportRQ
    );

    /**
     * 推送房价
     */
    @WebMethod(operationName = "OTA_HotelRatePlanNotifRQ", action = "http://htng.org/2014B/HTNG_ARIAndReservationPushService#OTA_HotelRatePlanNotifRQ")
    @WebResult(name = "OTA_HotelRatePlanNotifRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "OTA_HotelRatePlanNotifRQResult")
    public OTAHotelRatePlanNotifRS otaHotelRatePlanNotifRQ(
        @WebParam(partName = "OTA_HotelRatePlanNotifRQ1", name = "OTA_HotelRatePlanNotifRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        OTAHotelRatePlanNotifRQ otaHotelRatePlanNotifRQ1
    );

    /**
     * 库存(实时房量)
     */
    @WebMethod(operationName = "OTA_HotelInvCountNotifRQ", action = "http://htng.org/2014B/HTNG_ARIAndReservationPushService#OTA_HotelInvCountNotifRQ")
    @WebResult(name = "OTA_HotelInvCountNotifRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "OTA_HotelInvCountNotifRQResult")
    public OTAHotelInvCountNotifRS otaHotelInvCountNotifRQ(
        @WebParam(partName = "OTA_HotelInvCountNotifRQ1", name = "OTA_HotelInvCountNotifRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        OTAHotelInvCountNotifRQ otaHotelInvCountNotifRQ1
    );

    /**
     * 可用房态，最大可卖数(保留房)
     */
    @WebMethod(operationName = "OTA_HotelAvailNotifRQ", action = "http://htng.org/2014B/HTNG_ARIAndReservationPushService#OTA_HotelAvailNotifRQ")
    @WebResult(name = "OTA_HotelAvailNotifRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "OTA_HotelAvailNotifRQResult")
    public OTAHotelAvailNotifRS otaHotelAvailNotifRQ(
        @WebParam(partName = "OTA_HotelAvailNotifRQ1", name = "OTA_HotelAvailNotifRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        OTAHotelAvailNotifRQ otaHotelAvailNotifRQ1
    );

    /**
     * 拉取预授权
     */
    @WebMethod(operationName = "PmsRetrivePrdInfo", action = "http://htng.org/2014B/HTNG_ARIAndReservationPullService#RetrievepPrdInfo")
    @WebResult(name = "OrderPaymentInfoRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "PmsRetrivePrdInfoResult")
    public OrderPaymentInfoRS pmsRetrivePrdInfo(
        @WebParam(partName = "OTA_ReadRQ", name = "OTA_PrdReadRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        OTAPrdReadRQ otaReadRQ
    );

    /**
     * 订单状态推送
     */
    @WebMethod(operationName = "PmsOrderStatusPush", action = "http://htng.org/2014B/HTNG_ARIAndReservationPushService#OrderStatusPush")
    @WebResult(name = "OTA_PushOrderStatusRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "PmsOrderStatusPushResult")
    public OTAPushOrderStatusRS pmsOrderStatusPush(
        @WebParam(partName = "OTA_PushOrderStatusRQ", name = "OTA_PushOrderStatusRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        OTAPushOrderStatusRQ otaPushOrderStatusRQ
    );

    /**
     * 拉取订单
     */
    @WebMethod(operationName = "RetrieveReservations", action = "http://htng.org/2014B/HTNG_ARIAndReservationPullService#RetrieveReservations")
    @WebResult(name = "OTA_ResRetrieveRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "RetrieveReservationsResult")
    public OTAResRetrieveRS retrieveReservations(
        @WebParam(partName = "OTA_ReadRQ", name = "OTA_ReadRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        OTAReadRQ otaReadRQ
    );

    /**
     * 预授权---离店
     */
    @WebMethod(operationName = "PmsCheckedOutNotice", action = "http://htng.org/2014B/HTNG_ARIAndReservationPushService#OrderApplyPaymentRQ")
    @WebResult(name = "OrderApplyPaymentRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "PmsCheckedOutNoticeResult")
    public OrderApplyPaymentRS pmsCheckedOutNotice(
        @WebParam(partName = "OrderApplyPaymentRQ", name = "OrderApplyPaymentRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        OrderApplyPaymentRQ orderApplyPaymentRQ
    );

    /**
     * 确认订单
     */
    @WebMethod(operationName = "UpdatePulledReservations", action = "http://htng.org/2014B/HTNG_ARIAndReservationPullService#UpdatePulledReservations")
    @WebResult(name = "OTA_NotifReportRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "UpdatePulledReservationsResult")
    public MessageAcknowledgementType updatePulledReservations(
        @WebParam(partName = "OTA_NotifReportRQ", name = "OTA_NotifReportRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05")
        OTANotifReportRQ otaNotifReportRQ
    );
}
