
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ota.jw.PMSGateway;

import java.util.logging.Logger;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-25T14:50:06.441+08:00
 * Generated source version: 3.2.4
 *
 */

@javax.jws.WebService(
                      serviceName = "PMSGatewayService",
                      portName = "PMSGatewayServiceHttpPost",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "http://124.127.242.67:38196/PMSGateway/PMSGatewayService.asmx?WSDL",
                      endpointInterface = "ota.jw.PMSGateway.PMSGatewayServiceHttpPost")

public class PMSGatewayServiceHttpPostImpl implements PMSGatewayServiceHttpPost {

    private static final Logger LOG = Logger.getLogger(PMSGatewayServiceHttpPostImpl.class.getName());

}
