package ota.jw.PMSGateway;

import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-25T14:50:06.467+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "PMSGatewayServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
public interface PMSGatewayServiceHttpPost {
}
