
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ota.jw.PMSGateway;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-25T14:50:06.414+08:00
 * Generated source version: 3.2.4
 *
 */

@javax.jws.WebService(
                      serviceName = "PMSGatewayService",
                      portName = "PMSGatewayServiceSoap",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "http://124.127.242.67:38196/PMSGateway/PMSGatewayService.asmx?WSDL",
                      endpointInterface = "ota.jw.PMSGateway.PMSGatewayServiceSoap")

public class PMSGatewayServiceSoapImpl implements PMSGatewayServiceSoap {

    private static final Logger LOG = Logger.getLogger(PMSGatewayServiceSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see ota.jw.PMSGateway.PMSGatewayServiceSoap#otaHotelStayInfoNotifRQ(ota.jw.PMSGateway.OTAHotelStayInfoNotifRQ otaHotelRatePlanNotifRQ1)*
     */
    public ota.jw.PMSGateway.OTAHotelStayInfoNotifRS otaHotelStayInfoNotifRQ(OTAHotelStayInfoNotifRQ otaHotelRatePlanNotifRQ1) {
        LOG.info("Executing operation otaHotelStayInfoNotifRQ");
        System.out.println(otaHotelRatePlanNotifRQ1);
        try {
            ota.jw.PMSGateway.OTAHotelStayInfoNotifRS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ota.jw.PMSGateway.PMSGatewayServiceSoap#pmsInHouseNotice(ota.jw.PMSGateway.OrderCheckInNoticeRQ orderCheckInNoticeRQ)*
     */
    public ota.jw.PMSGateway.OrderCheckInNoticeRS pmsInHouseNotice(OrderCheckInNoticeRQ orderCheckInNoticeRQ) {
        LOG.info("Executing operation pmsInHouseNotice");
        System.out.println(orderCheckInNoticeRQ);
        try {
            ota.jw.PMSGateway.OrderCheckInNoticeRS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ota.jw.PMSGateway.PMSGatewayServiceSoap#updateRetrievedPrdStatus(ota.jw.PMSGateway.OTAPrdNotifReportRQ otaNotifReportRQ)*
     */
    public ota.jw.PMSGateway.MessageAcknowledgementType updateRetrievedPrdStatus(OTAPrdNotifReportRQ otaNotifReportRQ) {
        LOG.info("Executing operation updateRetrievedPrdStatus");
        System.out.println(otaNotifReportRQ);
        try {
            ota.jw.PMSGateway.MessageAcknowledgementType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ota.jw.PMSGateway.PMSGatewayServiceSoap#otaHotelRatePlanNotifRQ(ota.jw.PMSGateway.OTAHotelRatePlanNotifRQ otaHotelRatePlanNotifRQ1)*
     */
    public ota.jw.PMSGateway.OTAHotelRatePlanNotifRS otaHotelRatePlanNotifRQ(OTAHotelRatePlanNotifRQ otaHotelRatePlanNotifRQ1) {
        LOG.info("Executing operation otaHotelRatePlanNotifRQ");
        System.out.println(otaHotelRatePlanNotifRQ1);
        try {
            ota.jw.PMSGateway.OTAHotelRatePlanNotifRS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ota.jw.PMSGateway.PMSGatewayServiceSoap#otaHotelInvCountNotifRQ(ota.jw.PMSGateway.OTAHotelInvCountNotifRQ otaHotelInvCountNotifRQ1)*
     */
    public ota.jw.PMSGateway.OTAHotelInvCountNotifRS otaHotelInvCountNotifRQ(OTAHotelInvCountNotifRQ otaHotelInvCountNotifRQ1) {
        LOG.info("Executing operation otaHotelInvCountNotifRQ");
        System.out.println(otaHotelInvCountNotifRQ1);
        try {
            ota.jw.PMSGateway.OTAHotelInvCountNotifRS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ota.jw.PMSGateway.PMSGatewayServiceSoap#otaHotelAvailNotifRQ(ota.jw.PMSGateway.OTAHotelAvailNotifRQ otaHotelAvailNotifRQ1)*
     */
    public ota.jw.PMSGateway.OTAHotelAvailNotifRS otaHotelAvailNotifRQ(OTAHotelAvailNotifRQ otaHotelAvailNotifRQ1) {
        LOG.info("Executing operation otaHotelAvailNotifRQ");
        System.out.println(otaHotelAvailNotifRQ1);
        try {
            ota.jw.PMSGateway.OTAHotelAvailNotifRS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ota.jw.PMSGateway.PMSGatewayServiceSoap#pmsRetrivePrdInfo(ota.jw.PMSGateway.OTAPrdReadRQ otaReadRQ)*
     */
    public ota.jw.PMSGateway.OrderPaymentInfoRS pmsRetrivePrdInfo(OTAPrdReadRQ otaReadRQ) {
        LOG.info("Executing operation pmsRetrivePrdInfo");
        System.out.println(otaReadRQ);
        try {
            ota.jw.PMSGateway.OrderPaymentInfoRS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ota.jw.PMSGateway.PMSGatewayServiceSoap#pmsOrderStatusPush(ota.jw.PMSGateway.OTAPushOrderStatusRQ otaPushOrderStatusRQ)*
     */
    public ota.jw.PMSGateway.OTAPushOrderStatusRS pmsOrderStatusPush(OTAPushOrderStatusRQ otaPushOrderStatusRQ) {
        LOG.info("Executing operation pmsOrderStatusPush");
        System.out.println(otaPushOrderStatusRQ);
        try {
            ota.jw.PMSGateway.OTAPushOrderStatusRS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ota.jw.PMSGateway.PMSGatewayServiceSoap#retrieveReservations(ota.jw.PMSGateway.OTAReadRQ otaReadRQ)*
     */
    public ota.jw.PMSGateway.OTAResRetrieveRS retrieveReservations(OTAReadRQ otaReadRQ) {
        LOG.info("Executing operation retrieveReservations");
        System.out.println(otaReadRQ);
        try {
            ota.jw.PMSGateway.OTAResRetrieveRS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ota.jw.PMSGateway.PMSGatewayServiceSoap#pmsCheckedOutNotice(ota.jw.PMSGateway.OrderApplyPaymentRQ orderApplyPaymentRQ)*
     */
    public ota.jw.PMSGateway.OrderApplyPaymentRS pmsCheckedOutNotice(OrderApplyPaymentRQ orderApplyPaymentRQ) {
        LOG.info("Executing operation pmsCheckedOutNotice");
        System.out.println(orderApplyPaymentRQ);
        try {
            ota.jw.PMSGateway.OrderApplyPaymentRS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ota.jw.PMSGateway.PMSGatewayServiceSoap#updatePulledReservations(ota.jw.PMSGateway.OTANotifReportRQ otaNotifReportRQ)*
     */
    public ota.jw.PMSGateway.MessageAcknowledgementType updatePulledReservations(OTANotifReportRQ otaNotifReportRQ) {
        LOG.info("Executing operation updatePulledReservations");
        System.out.println(otaNotifReportRQ);
        try {
            ota.jw.PMSGateway.MessageAcknowledgementType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
