package pms.order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2017-01-10T11:18:00.068+08:00
 * Generated source version: 2.7.10
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServiceSoap {

    /**
     * 可定检查
     */
    @WebResult(name = "OTA_HotelAvailRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "CheckHotelAvailabilityResult")
    @WebMethod(operationName = "CheckHotelAvailability", action = "http://htng.org/2014B/HTNG_SeamlessShopAndBookService#CheckAvailability")
    public OTAHotelAvailRS checkHotelAvailability(@WebParam(partName = "otaHoelResRQ", name = "OTA_HotelAvailRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05") OTAHotelAvailRQ otaHoelResRQ);

    /**
     * 预定、修改、取消
     */
    @WebResult(name = "OTA_HotelResRS", targetNamespace = "http://www.opentravel.org/OTA/2003/05", partName = "BookingActionResult")
    @WebMethod(operationName = "BookingAction", action = "http://htng.org/2014B/HTNG_SeamlessShopAndBookService#ProcessReservationRequest")
    public HotelResResponseType bookingAction(@WebParam(partName = "otaHoelResRQ", name = "OTA_HotelResRQ", targetNamespace = "http://www.opentravel.org/OTA/2003/05") OTAHotelResRQ otaHoelResRQ);
}
